CWLang:AddTranslation('ru',{
    ['Hello there'] = 'Приветствую',
    Welcome = 'Добро пожаловать',
    ['The changes was saved'] = 'Изменения сохранены',
    ['Save changes'] = 'Сохранить изменения',
    ['You have no access rights to server configuration'] = 'У Вас нет прав для доступа к конфигурации сервера',
    Config = 'Конфигурация',
    Sort = 'Сортировать',
    ['Addons Configuration'] = 'Конфигурация Аддонов',
    Configurer = 'Конфигуратор',
    Add = 'Добавить',
    Remove = 'Удалить',
    ['Insert new value'] = 'Введите новое значение',
    ['Light theme'] = 'Светлая тема',
    Main = 'Основное',
})