project = "Gmod Nlit's Base Framework"
title = "Nlit's Framework documentation"
description = "This is base contains a lot of useful functions for easy development of UI, working with database, and other things that programmers is usually do"
format = "discount"
backtick_references = false
file = "lua"
dir = "ldoc"
readme = "README.md"
style = "!new"
kind_names = {
   topic = "Manual",
   script = "Programs"
}
examples  =  {
}
-- vim: ft=lua